### ISSUE TITLE
apple dictionary

### ISSUE THREAD

**Issue by pnasimi** [dolanskurd/Daneshjoo#1]
hi, thank you for efforts , how to load these glossary to apple dictionary in macos?

**Comment by 0xdolan** [comment]
> hi, thank you for efforts , how to load these glossary to apple dictionary in macos?

Hey! You are welcome. You can use GoldenDictionary. Or MDict. 
Search, probably there are new apps also. For iOS you can use [Eudic](https://apps.apple.com/app/id367278030). It is a new app.
